In [3]:
import cv2

In [5]:
import cv2

# Create a video capture object
cap = cv2.VideoCapture(0)  # 0 refers to the default camera

In [20]:
while True:
    ret, frame = cap.read()
    coords = detect_face(frame)
    for x,y,w,h in coords:
        print(x,y,w,h)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),3)
    cv2.imshow('window',frame)
    if(cv2.waitKey(1) & 0xFF == ord('x')):
        break
cv2.destroyAllWindows()

()
()
[[ 72 134  83  83]]
72 134 83 83
[[ 23 165  86  86]]
23 165 86 86
[[113  96  84  84]]
113 96 84 84
()
[[ 65 106 246 246]
 [255 152 196 196]]
65 106 246 246
255 152 196 196
[[106 127 243 243]]
106 127 243 243
[[100 122 245 245]]
100 122 245 245
[[300 185 150 150]
 [102 130 230 230]]
300 185 150 150
102 130 230 230
[[110 139 221 221]]
110 139 221 221
[[ 99 129 236 236]]
99 129 236 236
[[ 94 129 240 240]]
94 129 240 240
[[ 92 124 240 240]]
92 124 240 240
[[ 86 119 256 256]]
86 119 256 256
[[ 88 123 247 247]]
88 123 247 247
[[ 80 124 246 246]]
80 124 246 246
[[ 81 129 242 242]]
81 129 242 242
[[ 82 128 244 244]]
82 128 244 244
[[ 90 134 228 228]]
90 134 228 228
[[ 87 133 238 238]]
87 133 238 238
[[ 88 130 244 244]]
88 130 244 244
[[ 88 130 244 244]]
88 130 244 244
[[ 94 141 234 234]]
94 141 234 234
[[ 83 130 253 253]]
83 130 253 253
[[ 86 138 239 239]]
86 138 239 239
[[ 89 135 240 240]]
89 135 240 240
[[ 84 126 246 246]]
84 126 246 246
[[ 79 123 254 254]]
79 123 254 254
[[ 76 122 258

KeyboardInterrupt: 

In [8]:
haar = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [44]:
def detect_face(img):
    coords = haar.detectMultiScale(img)
    print(coords)
    return coords

In [45]:
import numpy as np
import ast

In [49]:
while True:
    ret, frame = cap.read()
    coords = detect_face(frame)
    for x,y,w,h in coords:
        print(x,y,w,h)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),3)
  #CALL DETECTION FN
    img = cv2.resize(frame,(224,224))
    y_pred = detect_face_mask(img)
    # pred = (y_pred >= 0.5).astype(int)
  # print(pred)
    if y_pred == 0:
        draw_label(frame,'Mask Detected',(30,30),(0,255,0))
    else:
        draw_label(frame,'No Mask',(30,30),(0,0,255))

    cv2.imshow('window',frame)
    if(cv2.waitKey(1) & 0xFF == ord('X')):
        break
    # Check if the window is closed (alternative way)
    if cv2.getWindowProperty('window', cv2.WND_PROP_VISIBLE) < 1:
        break

cv2.release()
cv2.destroyAllWindows()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()


KeyboardInterrupt: 

In [42]:
def detect_face_mask(img):
    # y_pred = model.predict(img.reshape(1,224,224,3))
  # return y_pred
    return 1;

In [43]:
def draw_label(img,text,pos,bg_color):
  text_size = cv2.getTextSize(text,cv2.FONT_HERSHEY_SIMPLEX,1,cv2.FILLED)
  end_x = pos[0] + text_size[0][0] + 2
  end_y = pos[1] + text_size[0][1] - 2

  cv2.rectangle(img,pos,(end_x,end_y),bg_color,cv2.FILLED)
  cv2.putText(img,text,pos,cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),1,cv2.LINE_AA)